[No ticket] More tolerant of expired refresh tokens when unlinking
DataBiosphere/bond pull request #156
Opened 2020-10-01 17:25 UTC by marctalbott

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary. Documentation PRs only need 1 thumb.
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2020-10-01 17:36 UTC, dvoet requested changes

2020-10-01 17:36 UTC, dvoet commented on bond_app/fence_api.py
> +        if result.status_code // 100 != 2 or result.status_code // 100 != 4:
this should be `and` not `or`

2020-10-01 18:39 UTC, gpolumbo-broad requested changes

2020-10-01 18:39 UTC, gpolumbo-broad commented on bond_app/fence_api.py
> +        if result.status_code // 100 != 2 and result.status_code // 100 != 4:
Can we leave a comment here on why we are accepting `4xx` as OK.

2020-10-01 18:44 UTC, gpolumbo-broad commented
And I'm still an advocate of directly deleting the item from the cache when we know we can remove it at deletion time rather than waiting for the expiry logic to purge it, but I don't have a good technical or logical reason why need to do it, so it's fine.  To me, it's sort of like dropping a piece of trash on the street when I see the street sweeper coming.  It's going to get swept up, so I can just leave it, but I'm probably going to pick it up and throw it in the trash. :)

2020-10-01 18:47 UTC, marctalbott commented
> And I'm still an advocate of directly deleting the item from the cache when we know we can remove it at deletion time rather than waiting for the expiry logic to purge it, but I don't have a good technical or logical reason why need to do it, so it's fine. To me, it's sort of like dropping a piece of trash on the street when I see the street sweeper coming. It's going to get swept up, so I can just leave it, but I'm probably going to pick it up and throw it in the trash. :)

We were directly deleting SA keys that had been associated with user ids from the cache. We don't do that anymore after #155 because of the discrepancy it was causing between pets and users calling Bond. That's why this PR removes that direct deletion, since there's no longer anything to delete

2020-10-01 19:05 UTC, gpolumbo-broad approved these changes

2020-10-02 15:38 UTC, dvoet approved these changes

2020-10-02 19:57 UTC, merged