CA-1109 Adding logging
DataBiosphere/bond pull request #159
Opened 2020-12-17 17:58 UTC by gpolumbo-broad

I _think_ the issue has to do with the fact that "acquiring a lock" on a FenceServiceAccount record in Datastore can fail because the record is either already locked, or if the Datastore transaction throws any kind of exception for any reason, which, according to Google's documentation, is a possible thing:  https://cloud.google.com/appengine/docs/standard/python/datastore/transactions#using_transactions

At this time, we don't know if this is what's happening (because any exceptions here are swallowed) or if something else is going on.  Bond could really use a bunch more logging in general, so I added several log statements in the whole "get Key" flow that hopefully will help to debug this (and future) issue(s).  

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary. Documentation PRs only need 1 thumb.
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2020-12-17 18:13 UTC, dvoet requested changes

2020-12-17 18:13 UTC, dvoet commented on bond_app/fence_api.py
> +                     .format(self.credentials_google_url, result.status_code, result.content))
The content being logged here is a service account key with access to protected data! Definitely don't log that.

2020-12-17 18:13 UTC, dvoet commented on bond_app/fence_token_storage.py
> +        but at the moment, we don't know what those exceptions might be nor what they mean.
It looks like the comments below cover this case. In any case, I think it is inappropriate to commit debug comments like this.

2020-12-17 18:13 UTC, dvoet commented on bond_app/fence_token_storage.py
> +            logging.info("Could not obtain lock on {} because it is already locked".format(fence_service_account))
I think this is debug level

2020-12-17 18:13 UTC, dvoet commented on bond_app/fence_token_storage.py
> +        logging.info("Successfully locked FenceServiceAccount Record: {}".format(fence_service_account))
I think this is debug level

2020-12-17 18:55 UTC, andy7i approved these changes
These look like potentially very helpful changes, bubbling up the exception and enabling local logging. 👍 with the changes doug requested.

2020-12-20 03:23 UTC, dvoet commented on bond_app/fence_api.py
> +        # Logging of the `response.content` can probably be removed after we have resolved this issue
already gone

2020-12-20 03:23 UTC, dvoet approved these changes

2021-01-15 15:27 UTC, dvoet approved these changes

2021-01-15 15:54 UTC, andy7i approved these changes
👍  the comments help a lot to describe what's going on
did some light testing and saw the logs as expected

2021-01-15 15:54 UTC, andy7i commented on bond_app/fence_api.py
> +            logger.debug("Scrubbed {}: {}".format(name, scrubbed_json_result))
verified that it works locally!

```
2021-01-15 10:46:38,738 - bond_app.fence_api - DEBUG - Getting new Service Account JSON Key from Fence via - request: POST https://us-central1-broad-dsde-dev.cloudfunctions.net/user/credentials/google - status code: 200 -
2021-01-15 10:46:38,739 - bond_app.fence_api - DEBUG - Scrubbed Service Account Key JSON: {'auth_provider_x509_cert_url': 'https://www.googleapis.com/oauth2/v1/certs', 'auth_uri': 'https://accounts.google.com/o/oauth2/auth', 'client_email': 'mock-provider-user-service-acc@broad-dsde-dev.iam.gserviceaccount.com', 'client_id': '102327840668511205237', 'client_x509_cert_url': 'https://www.googleapis.com/robot/v1/metadata/x509/mock-provider-user-service-acc%40broad-dsde-dev.iam.gserviceaccount.com', 'private_key': '[REDACTED]', 'private_key_id': '9d41d414182a8ff73f944ee89d67c605d1821589', 'project_id': 'broad-dsde-dev', 'token_uri': 'https://oauth2.googleapis.com/token', 'type': 'service_account'}
2021-01-15 10:46:38,746 - werkzeug - INFO - 127.0.0.1 - - [15/Jan/2021 10:46:38] "GET /api/link/v1/dcf-fence/serviceaccount/key HTTP/1.1" 200 -
```

2021-01-15 21:21 UTC, gpolumbo-broad commented
jenkins retest

2021-01-19 14:21 UTC, merged